function idxInGroup = leafnodes(NodeId, link)
% leafnodesid finds all leaf nodes for a given group node id
% in a linkage matrix.
%
%% INPUTS:
% NodeId - generated in qdiag()
% link - linkage matrix generated by linkage() fn when calling hrpestimate


% Author: Nina Matthews (2023)

% $Revision: 1.2 $ $Date: 2023/02/20 16:10:46 $ $Author: Nina Matthews $


%% 
N= size(link, 1)+1;
if NodeId>N
    gNodeIds = link(NodeId-N, 1:2);
    idxInGroup = [leafnodes(gNodeIds(1), link), ...
        leafnodes(gNodeIds(2), link)];
else
    idxInGroup = NodeId;
end
end