function sortedIdx = qdiag(link)
% qdiag sub-function of HRP estimate performs the quasi-diagonalization
% qdiag orders the nodes according to the similarities
% specified by linkage matrix.

% INPUTS:
% link - generated by linkage() when hrpestimate is called. 

%% 
nLeafNodes = size(link, 1) + 1;
rootNodeId = 2*nLeafNodes-1;
sortedIdx = leafnodes(rootNodeId, link);
end
