function sortedIdx = qdiag(link)
% qdiag sub-function of HRP estimate performs the quasi-diagonalization
% qdiag orders the nodes according to the similarities
% specified by linkage matrix.
%
%% INPUTS:
% link - generated by linkage() when hrpestimate is called. 


% Author: Nina Matthews (2023)

% $Revision: 1.2 $ $Date: 2023/02/20 16:10:46 $ $Author: Nina Matthews $


%% 
nLeafNodes = size(link, 1) + 1;
rootNodeId = 2*nLeafNodes-1;
sortedIdx = leafnodes(rootNodeId, link);
end
