function EfNumScenarios = ens(p, type, gamma)
% Calculates the Effective Number of Scenarios using Meucci's more general
% expression: J_hat = (Sum(p^gamma)^(-1/(gamma -1)).

% If type is not specified or gamma = 1 or not specified, the 
% exponential of the entropy expression is used: e^-sum(p*ln(p))

%% INPUTS:

% p - flexible probability series (typically generated by entropy pooling
% approach with an exponential prior). 
% (Type: array [1 x T])

% type - only 'ExpEntropy' will trigger a specific action: resulting in
% gamma = 1 and the use of the exponential of the entropy expression being
% used.
% (Type: string|char)

% gamma - used in the generalised expression.
% (Type: double)

%%
if nargin < 2 || isempty(type) || gamma == 1
    type = 'ExpEntropy';
end

if nargin < 3 || isempty(gamma)
    gamma = 1;
end

% Calculate Effective Number of Scenarios using 

if strcmp(type, 'ExpEntropy')
    p(p==0) = 10^-250; 
    EfNumScenarios = exp(-p * log(p'));
else
    p(p==0) = 10^-250; 
    pwr = (-1/(gamma-1));
    EfNumScenarios = sum(p .^ gamma) ^ pwr;
end
end

